### ISSUE TITLE
furniture for booth

### ISSUE THREAD

**Issue by bendichter** [dandi/sfn2023#1]

**Comment by bendichter** [comment]
https://docs.google.com/spreadsheets/d/1_6rIfYCC5nXEm4XqPleX0jXAOs7lyUhRxB3ct-4yPTg/edit#gid=0

**Comment by yarikoptic** [comment]
it was ordered

**Comment by yarikoptic** [comment]
FWIW -- I also ordered 5x5 ft banner with DANDI logo on one side and NWB on the other (so we could change depending on the weather)
